import pop

OPWord = pop.WordC('op')
VARWord =  pop.WordC('var')
QUOTEWord = pop.WordC('"')
IFWord = pop.WordC("if")
THENWord = pop.WordC("then")
ELSEWord = pop.WordC("else")
FIWord = pop.WordC("fi")
CALLWord = pop.WordC("call")
YCALLWord = pop.WordC("ycall")
ACTUALWord = pop.WordC("actual")
GLOBALWord = pop.WordC("global")
WHEREWord = pop.WordC("where")
ENDWord = pop.WordC("end")
EQUALWord = pop.WordC("=")
SEMICOLONWord = pop.WordC(";")
VALOFWord = pop.WordC("valof")
LLISTPARENWord = pop.WordC("[%")
RLISTPARENWord = pop.WordC("%]")
LSETPARENWord = pop.WordC("{%")
RSETPARENWord = pop.WordC("%}")
OUTPUTWord = pop.WordC("output")
IDWord = pop.WordC("id")
EODWord = pop.WordC("eod")

TRUEWord = pop.WordC('true')
FALSEWord = pop.WordC('false')